#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import editor.template_builders as build_template_ks

env["BUILDERS"]["MakeGDTemplateBuilder"] = Builder(
    action=env.Run(build_template_ks.make_templates),
    suffix=".h",
    src_suffix=".voy",
)

# Template files
templates_sources = Glob("*/*.voy")

env.Alias("editor_template_ks", [env.MakeGDTemplateBuilder("templates.gen.h", templates_sources)])
