name: 🤖 Android Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  KOSMIC_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes strict_checks=yes

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-android
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor)
            cache-name: android-editor
            target: editor
            tests: false
            sconsflags: arch=arm64 production=yes swappy=yes
            cache-limit: 1

          - name: Template arm32 (target=template_release, arch=arm32)
            cache-name: android-template-arm32
            target: template_release
            tests: false
            sconsflags: arch=arm32 swappy=yes
            cache-limit: 1

          - name: Template arm64 (target=template_release, arch=arm64)
            cache-name: android-template-arm64
            target: template_release
            tests: false
            sconsflags: arch=arm64 swappy=yes
            cache-limit: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Restore Kosmic build cache
        uses: ./.github/actions/kosmic-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/kosmic-deps

      - name: Download pre-built Android Swappy Frame Pacing Library
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: darksylinc/kosmic-swappy
          version: tags/v2023.3.0.0
          file: kosmic-swappy.7z
          target: swappy/kosmic-swappy.7z

      - name: Extract pre-built Android Swappy Frame Pacing Library
        run: 7za x -y swappy/kosmic-swappy.7z -o${{github.workspace}}/thirdparty/swappy-frame-pacing

      - name: Compilation
        uses: ./.github/actions/kosmic-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: android
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}
          scons-cache-limit: ${{ matrix.cache-limit }}

      - name: Save Kosmic build cache
        uses: ./.github/actions/kosmic-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Generate Kosmic templates
        if: matrix.target == 'template_release'
        run: |
          cd platform/android/java
          ./gradlew generateKosmicTemplates
          cd ../../..
          ls -l bin/

      - name: Generate Kosmic editor
        if: matrix.target == 'editor'
        run: |
          cd platform/android/java
          ./gradlew generateKosmicEditor
          ./gradlew generateKosmicHorizonOSEditor
          cd ../../..
          ls -l bin/android_editor_builds/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
