name: 🪲 Kosmic CPP
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  KOSMIC_BASE_BRANCH: main
  # Used for the kosmic-cpp checkout.
  KOSMIC_CPP_BRANCH: 1.0

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-cpp-tests
  cancel-in-progress: true

jobs:
  godot-cpp-tests:
    runs-on: ubuntu-24.04
    name: Build and test Kosmic CPP
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            misc/utility/problem-matchers.json

      - name: Checkout godot-cpp
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: kosmicengine/kosmic-cpp
          ref: ${{ env.KOSMIC_CPP_BRANCH }}
          path: kosmic-cpp

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download KSExtension interface and API dump
        uses: ./.github/actions/download-artifact
        with:
          name: godot-api-dump
          path: ./godot-cpp/ksextension

      # TODO: Enable caching when godot-cpp has proper cache limiting.

      # - name: Restore Kosmic build cache
      #   uses: ./.github/actions/godot-cache-restore
      #   with:
      #     cache-name: godot-cpp
      #   continue-on-error: true

      - name: Build godot-cpp test extension
        run: scons --directory=./godot-cpp/test target=template_debug dev_build=yes verbose=yes

      # - name: Save Kosmic build cache
      #   uses: ./.github/actions/godot-cache-save
      #   with:
      #     cache-name: godot-cpp
      #   continue-on-error: true
